// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCprrndYyNiRjUh-K3iZF5iFMeTwmeqRLs',
    appId: '1:384554601765:web:f5cfc9c971b97e45805ecc',
    messagingSenderId: '384554601765',
    projectId: 'hero-app-87dce',
    authDomain: 'hero-app-87dce.firebaseapp.com',
    storageBucket: 'hero-app-87dce.appspot.com',
    measurementId: 'G-JEDXV9MF2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCobtJx7sk_lCWaCuMcUxECHrqI7hyGnk',
    appId: '1:384554601765:android:ddf806ca68814629805ecc',
    messagingSenderId: '384554601765',
    projectId: 'hero-app-87dce',
    storageBucket: 'hero-app-87dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ciakSrU3M4lg-JRus23iKBbU_jb1ccM',
    appId: '1:384554601765:ios:4397061bc8158eff805ecc',
    messagingSenderId: '384554601765',
    projectId: 'hero-app-87dce',
    storageBucket: 'hero-app-87dce.appspot.com',
    iosClientId: '384554601765-r1muf7up1261kvorqepdlojpmeqjgf7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.heroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ciakSrU3M4lg-JRus23iKBbU_jb1ccM',
    appId: '1:384554601765:ios:a002ec26743e3cdc805ecc',
    messagingSenderId: '384554601765',
    projectId: 'hero-app-87dce',
    storageBucket: 'hero-app-87dce.appspot.com',
    iosClientId: '384554601765-go4s50a0rtvfvlnc89p0643265be68rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.heroApp.RunnerTests',
  );
}
